fix: minor changes to run code signing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,6 +49,18 @@ jobs:
       - run:
           name: Import Code Signing Certificate
           command: |
+            if ! command -v nvm &> /dev/null; then
+              echo "nvm could not be found, installing..."
+              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
+              export NVM_DIR="$HOME/.nvm"
+              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+            fi
+            # if NVM was installed in $HOME:
+            [ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh"
+
+            nvm install v18.18.0
+            nvm use v18.18.0
+            
             chmod +x packaging/add-osx-cert.sh
             packaging/add-osx-cert.sh
             npm run dist:macArm
